Repository Project-Chirp/chirp-backend, pull requests merged in 2023-07, with the labels that each got.

#31 T30: PostParentId and Boolean Return
  controllers/PostController.js
  database/03_Remove_isReply.sql
  models/PostModel.js
Labels: tech debt

#33 T32: Fix profile queries after removal of isReply column from database
  database/03_Add_Bio.sql
  database/04_Remove_isReply.sql
  models/ProfileModel.js
Labels: bug

#28 T27: Message Modal Endpoint
  controllers/MessagesController.js
  models/MessagesModel.js
  routes/messagesRoutes.js
Labels: feature

#39 T38: Update post queries to include number of replies and reposts
  models/PostModel.js
  models/ProfileModel.js
Labels: feature, tech debt
